### ISSUE TITLE
add json support for SQS

### ISSUE THREAD

**Issue by fabriciogpp** [p4tin/goaws#116]
This is the best emulator I could find, unfortunately I'm using Spring Boot and our API accepts only JSON. It seems you only support XML for SQS, so I get:

```
c.a.http.DefaultErrorResponseHandler     : Unable to parse HTTP response (Invocation Id:0cd30c53-daa3-b1e8-4d99-cb64d5ee29fb) content to XML document 'Bad Request' 

org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:994)
etc.
```
I dunno if I'm doing something wrong, but in case you only support XML, I'd like to ask for json support. I would like to use this emulator so much. Thank you very much.

**Comment by p4tin** [comment]
@fabriciogpp I am not sure about Spring Boot but I do have examples for using goaws in java in the repo under examples - check that out and let me know if that helps.
