### ISSUE TITLE
Hangs on purge queue / crashes on delete queue.

### ISSUE THREAD

**Issue by kbkk** [p4tin/goaws#226]
Hi,

Using the latest docker image, whenever I call the purge queue endpoint I never get a response back (timeout), the console doesn't even indicate such request was made.

However when I call delete queue I get this:
```
| goroutine 26 [running]:
| runtime.throw(0x7d2a53, 0x21)
| 	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:617 +0x72 fp=0xc0004ad830 sp=0xc0004ad800 pc=0x42b922
| runtime.mapaccess2_faststr(0x75a620, 0xc000071110, 0xc00006f038, 0x2c, 0x2c, 0x7a51c0)
| 	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/map_faststr.go:116 +0x4a9 fp=0xc0004ad8a0 sp=0xc0004ad830 pc=0x4122e9
| github.com/p4tin/goaws/app/gosns.CreateTopic(0x8498e0, 0xc000374620, 0xc00037d200)
| 	/Users/p4tin/Dropbox/code/gocode/src/github.com/p4tin/goaws/app/gosns/gosns.go:114 +0xcf fp=0xc0004ad9c0 sp=0xc0004ad8a0 pc=0x70480f
| net/http.HandlerFunc.ServeHTTP(...)
| 	/usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:1995
| github.com/p4tin/goaws/app/router.actionHandler(0x8498e0, 0xc000374620, 0xc00037d200)
| 	/Users/p4tin/Dropbox/code/gocode/src/github.com/p4tin/goaws/app/router/router.go:79 +0x29f fp=0xc0004adb98 sp=0xc0004ad9c0 pc=0x70e00f
| net/http.HandlerFunc.ServeHTTP(0x7e1360, 0x8498e0, 0xc000374620, 0xc00037d200)
| 	/usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:1995 +0x44 fp=0xc0004adbc0 sp=0xc0004adb98 pc=0x648bf4
| github.com/gorilla/mux.(*Router).ServeHTTP(0xc000050f60, 0x8498e0, 0xc000374620, 0xc00037d200)
| 	/Users/p4tin/Dropbox/code/gocode/pkg/mod/github.com/gorilla/mux@v1.6.0/mux.go:150 +0x105 fp=0xc0004adcf0 sp=0xc0004adbc0 pc=0x6f1155
| net/http.serverHandler.ServeHTTP(0xc000079ba0, 0x8498e0, 0xc000374620, 0xc00037c600)
| 	/usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:2774 +0xa8 fp=0xc0004add20 sp=0xc0004adcf0 pc=0x64b238
| net/http.(*conn).serve(0xc000456460, 0x84a4a0, 0xc00036a580)
| 	/usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:1878 +0x851 fp=0xc0004adfc8 sp=0xc0004add20 pc=0x647da1
| runtime.goexit()
| 	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0004adfd0 sp=0xc0004adfc8 pc=0x457331
| created by net/http.(*Server).Serve
| 	/usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:2884 +0x2f4
```

Is there any additional info I can provide to help fixing this?

**Comment by Admiral-Piett** [comment]
@kbkk Is this still happening for you?  I'll try to recreate this as soon as I can, but if you have any more recent information about it that would be extremely helpful!
